apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs-calculadora
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: nodejs-calculadora
    spec:
      containers:
      - name: nodejs-calculadora
        image: juliopari/nodejs-calculadora:v1
        ports:
        - name: http
          containerPort: 3000
