apiVersion: v1
kind: Service
metadata:
  name: nodejs-calculadora
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
  selector:
    role: nodejs-calculadora
